---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - config.yaml

  tasks:
    - name: Install Python3 and Pip3 for ubuntu
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
      when: ansible_distribution == 'Ubuntu'

    - name: Install OpenJDK
      package:
        name: openjdk-11-jdk  
        state: present

    - name: Change Message of the day
      copy: 
       content: "\n"
       dest: /etc/motd
    
    - name: Disable default motd
      file: 
       dest: "/etc/update-motd.d/"
       mode: "u-x,g-x,o-x"
       state: directory
       recurse: yes

    - name: Set Pip3 as the default pip
      shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

    - name: Set Python3 as the default
      shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

    - name: Create user
      user: 
       name: ""
       comments: ""
       shell: /bin/bash
